### ISSUE TITLE
problem when use window operation

### ISSUE THREAD

**Issue by hongxiuzhe** [uber/AthenaX#15]
The sql "select * from input.transaction" is correct.

But the below sql "SELECT COUNT(1) AS total_record FROM input.transaction GROUP BY TUMBLE(proctime,INTERVAL '1' MINUTE)" is wrong. It seems that TUMBLE function is not registered.

2017-12-20 14:29:51,862 [pool-1-thread-1] WARN  jobs.WatchdogPolicyDefault (WatchdogPolicyDefault.java:onHealthCheckReport(62)) - Failed to instantiate the query 'SELECT COUNT(1) AS total_record FROM input.transaction GROUP BY TUMBLE(proctime,INTERVAL 1 MINUTE)' on foo
com.uber.athenax.vm.compiler.parser.impl.ParseException: Encountered "" at line 1, column 81.

	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.generateParseException(SqlParserImpl.java:23700)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.jj_consume_token(SqlParserImpl.java:23511)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.Arg(SqlParserImpl.java:760)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.FunctionParameterList(SqlParserImpl.java:696)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.NamedFunctionCall(SqlParserImpl.java:5200)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.AtomicRowExpression(SqlParserImpl.java:3219)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.Expression3(SqlParserImpl.java:3070)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.Expression2b(SqlParserImpl.java:2881)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.Expression2(SqlParserImpl.java:2905)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.Expression(SqlParserImpl.java:2860)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.GroupingElement(SqlParserImpl.java:2220)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.GroupingElementList(SqlParserImpl.java:2172)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.GroupByOpt(SqlParserImpl.java:2162)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.SqlSelect(SqlParserImpl.java:962)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.LeafQuery(SqlParserImpl.java:571)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.LeafQueryOrExpr(SqlParserImpl.java:2846)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.QueryOrExpr(SqlParserImpl.java:2768)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.OrderedQueryOrExpr(SqlParserImpl.java:490)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.SqlStmt(SqlParserImpl.java:793)
	at com.uber.athenax.vm.compiler.parser.impl.SqlParserImpl.SqlStmtsEof(SqlParserImpl.java:902)
	at com.uber.athenax.vm.compiler.planner.Planner.parse(Planner.java:102)
	at com.uber.athenax.vm.compiler.planner.Planner.sql(Planner.java:57)
	at com.uber.athenax.backend.server.jobs.JobManager.compile(JobManager.java:81)
	at com.uber.athenax.backend.server.jobs.WatchdogPolicyDefault.onHealthCheckReport(WatchdogPolicyDefault.java:59)
	at com.uber.athenax.backend.server.jobs.JobManager.onUpdatedInstances(JobManager.java:89)
	at com.uber.athenax.backend.server.yarn.InstanceManager.scanAll(InstanceManager.java:219)
	at com.uber.athenax.backend.server.yarn.InstanceManager$1.run(InstanceManager.java:71)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

@haohui

**Comment by haohui** [comment]
Hi,

I saw you asked the question on the mailing list -- issues is usually used to reporting bugs and working on fixes. Therefore I'm closing the issue.

Thanks!
