### ISSUE TITLE
Invalid location of the db--LevelDB

### ISSUE THREAD

**Issue by itzzy** [uber/AthenaX#41]
Exception in thread "main" java.lang.NullPointerException: Invalid location of the db
	at org.apache.flink.util.Preconditions.checkNotNull(Preconditions.java:75)
	at com.uber.athenax.backend.server.jobs.LevelDBJobStore.open(LevelDBJobStore.java:54)
	at com.uber.athenax.backend.server.ServerContext.start(ServerContext.java:63)
	at com.uber.athenax.backend.AthenaXServer.start(AthenaXServer.java:43)
	at com.uber.athenax.backend.AthenaXServer.main(AthenaXServer.java:67)

**Comment by ssyue** [comment]
--conf conf.yml

extras:
 foo: bar
 jobstore.leveldb.file: ./leveldb

**Comment by itzzy** [comment]
> --conf conf.yml
> 
> extras:
> foo: bar
> jobstore.leveldb.file: ./leveldb

最近要做一个基于flink的streaming SQL平台，看到这个项目，能否交流下，QQ：549926988

**Comment by ssyue** [comment]
> > --conf conf.yml
> > extras:
> > foo: bar
> > jobstore.leveldb.file: ./leveldb
> 
> 最近要做一个基于flink的streaming SQL平台，看到这个项目，能否交流下，QQ：549926988

我放弃了，这个太难用了。提交到yarn了，但是一直每隔2.8min就重启。

**Comment by zhaorongsheng** [comment]
这个项目缺少一些类啊？比如InstancesApiService、JobDefinition~~
