### ISSUE TITLE
fail to build project

### ISSUE THREAD

**Issue by qmz** [uber/AthenaX#43]
follow doc: 
$ git clone https://github.com/uber/AthenaX.git
$ mvn clean install

env : mac pro , java8 , maven 3.5

should I skip maven test ? It seem to fail to run yarn container test.

2019-06-23 23:49:03,242 [ContainersLauncher #0] WARN  nodemanager.DefaultContainerExecutor (DefaultContainerExecutor.java:launchContainer(230)) - Exception from container-launch with container ID: container_1561304918987_0001_01_000001 and exit code: 127
ExitCodeException exitCode=127: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:585)
	at org.apache.hadoop.util.Shell.run(Shell.java:482)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:776)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-06-23 23:49:03,244 [ContainersLauncher #0] INFO  nodemanager.ContainerExecutor (ContainerExecutor.java:logOutput(286)) - Exception from container-launch.
2019-06-23 23:49:03,244 [ContainersLauncher #0] INFO  nodemanager.ContainerExecutor (ContainerExecutor.java:logOutput(286)) - Container id: container_1561304918987_0001_01_000001
2019-06-23 23:49:03,244 [ContainersLauncher #0] INFO  nodemanager.ContainerExecutor (ContainerExecutor.java:logOutput(286)) - Exit code: 127
2019-06-23 23:49:03,244 [ContainersLauncher #0] INFO  nodemanager.ContainerExecutor (ContainerExecutor.java:logOutput(286)) - Stack trace: ExitCodeException exitCode=127: 
2019-06-23 23:49:03,244 [ContainersLauncher #0] INFO  nodemanager.ContainerExecutor (ContainerExecutor.java:logOutput(286)) - 	at org.apache.hadoop.util.Shell.runCommand(Shell.java:585)

**Comment by qmz** [comment]
use -DskipTests=true to build
